# Generated by Django 5.2.17 on 2026-08-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=256)),
                ('alternate_titles', models.JSONField(blank=True, default=list)),
                ('edition_info', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['title', 'author'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency_ms', models.IntegerField(default=0)),
                ('est_cost_usd', models.FloatField(default=0.0)),
                ('spines_detected', models.IntegerField(default=0)),
                ('spines_matched', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.CharField(max_length=512)),
                ('raw_author', models.CharField(blank=True, max_length=256)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source_image', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_entries', to='scanner.catalogbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
